//@ts-nocheck
'use client'
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Switch, Theme, ThemeContext } from "@radix-ui/themes";
import { useState } from "react";
// import { createContext } from "react";
// import { FavoriteProvider } from "./(home)/context/FavoriteContet";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export const  Themecontext = createContext();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
const [isDark , setIsDark ] = useState("light");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
     
      </body>
    </html>
  );
}
